db: 
  sauron: 
    master: 
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sauron?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: james
      password: admin
sql: 
  merchant: 
    add: insert into tbl_merchant (name, contact, address, status, remark) values (?, ?, ?, ?, ?)
    delete: delete from tbl_merchant where id=?
    update: update tbl_merchant set name=?, contact=?, address=?, status=?, remark=? where id=?
    get: select id, name, contact, address, status, remark, updated_at, created_at from tbl_merchant where id=?
    clear: truncate tbl_merchant
  balance:
    add: insert into tbl_balance (merchant_id, type, balance, status, total, description) values (?, ?, ?, ?, ?, ?)
    delete: delete from tbl_balance where id=?
    update: update tbl_balance set merchant_id=?, type=?, balance=?, status=?, total=?, description=? where id=?
    get: select id, merchant_id, type, balance, status, total, description, updated_at, created_at from tbl_balance where id=?
    getByMerchant: select id, merchant_id, type, balance, status, total, description, updated_at, created_at from tbl_balance where merchant_id=?
    clear: truncate tbl_balance 
