server: 
  port: 18888
spring: 
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/jameshang/my_config.git
          searchPaths: my-config/my-client, my-config/my-eureka-server, my-config/my-service
