server: 
  port: 8082
endpoints:
  sensitive: false
management:  
  port: 9002
  health:
    mail:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/
local:
  env:
    node: node2