server: 
  port: 8081
endpoints:
  sensitive: false
management:  
  port: 9001
  health:
    mail:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/
local:
  env:
    node: node1