server:
  port: 8763
endpoints:
  sensitive: false
eureka:
  instance:
    hostname: eureka-peer3
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/,http://eureka-peer4:8764/eureka/
