server:
  port: 8762
endpoints:
  sensitive: false
eureka:
  instance:
    hostname: eureka-peer2
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer3:8763/eureka/,http://eureka-peer4:8764/eureka/
