server:
  port: 8764
endpoints:
  sensitive: false
eureka:
  instance:
    hostname: eureka-peer4
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/,http://eureka-peer3:8763/eureka/
